#YES
LTO_ENABLE = yes
NKRO_ENABLE = yes
NO_PRINT = yes
NO_DEBUG = yes

#NO
RGB_MATRIX_ENABLE=no
RGBLIGHT_ENABLE = no
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
MUSIC_ENABLE = no
MOUSEKEY_ENABLE = no
EXTRAKEY_ENABLE = no
SPACE_CADET_ENABLE = no
GRAVE_ESC_ENABLE = no
MAGIC_ENABLE = no
MUSIC_ENABLE = no
